## isonim_email/style/metacraft_theme.nim — GENERATED, do not edit.
##
## The Metacraft product theme: required theme keys resolved to
## light/dark literals from the pinned design-system snapshot.
##   source:      https://github.com/metacraft-labs/codetracer-design-system/tree/8fb101f29a2269d87b246e87f6c39eff454f0a3a/brand/brand.json (and alias/alias.json, mapped/mapped.json)
##   repo:        https://github.com/metacraft-labs/codetracer-design-system
##   commit:      8fb101f29a2269d87b246e87f6c39eff454f0a3a
##   commit date: 2026-09-23
##   fetch date:  2026-09-27
##   brand:       brand.json d65d49db892c638b8ba221570bd76e3babc91668708bca8520fb5a7608be4b70
##   alias:       alias.json f84e6d9a3296501d188e2f9ebf7ad11d61317749919a83b60f0b740eb84f3ce2
##   mapped:      mapped.json deb29aad71b80a17eda81ae2c0b76f0ba268bb5e381dda7e2c436cf7757fad76
##   licence:     Metacraft-owned design tokens (no separate licence file; same organisation, public repo)
##
## Generated by `just theme-snapshot`
## (tools/theme-snapshot/snapshot.nim) from `mapping.json` over the
## pinned payloads: colours resolve from design-system roles (light
## inlines, dark feeds the head block); metrics and font stacks are
## email constants. Each entry cites its binding.
##
## Re-pinning is a deliberate PR: the diff shows which theme values
## changed. `tests/t4_theme_snapshot.nim` asserts this file is
## byte-identical to what the pinned inputs produce.

import isonim_email/style/tokens
import isonim_email/target

## The client families an edit to this module can change: read by
## the capture CLI to pick the families of an `--affected` run.
const affects*: set[ClientFamily] = allFamilies

const metacraftThemeSource* = "https://github.com/metacraft-labs/codetracer-design-system/tree/8fb101f29a2269d87b246e87f6c39eff454f0a3a/brand/brand.json (and alias/alias.json, mapped/mapped.json)"
const metacraftThemeCommit* = "8fb101f29a2269d87b246e87f6c39eff454f0a3a"
const metacraftThemeCommitDate* = "2026-09-23"
const metacraftThemeFetchDate* = "2026-09-27"
const metacraftThemeBrandSha256* = "d65d49db892c638b8ba221570bd76e3babc91668708bca8520fb5a7608be4b70"
const metacraftThemeAliasSha256* = "f84e6d9a3296501d188e2f9ebf7ad11d61317749919a83b60f0b740eb84f3ce2"
const metacraftThemeMappedSha256* = "deb29aad71b80a17eda81ae2c0b76f0ba268bb5e381dda7e2c436cf7757fad76"

proc metacraftTheme*(): EmailTheme =
  ## The Metacraft product theme: brand colours from
  ## `codetracer-design-system`, plus email constants.
  buildTheme([
    ("color.surface.canvas",
      ThemePair(light: "#d2ccc1", dark: "#1b1b1b")), # colors.ui.surface.base.canvas
    ("color.surface.card",
      ThemePair(light: "#dbd6cc", dark: "#262626")), # colors.ui.surface.base.card
    ("color.surface.subtle",
      ThemePair(light: "#e6e2db", dark: "#282828")), # colors.ui.surface.base.panel
    ("color.text.primary",
      ThemePair(light: "#272522", dark: "#f3f3f3")), # colors.ui.text.primary.body
    ("color.text.secondary",
      ThemePair(light: "#353430", dark: "#b4b4b4")), # colors.ui.text.primary.body-subtle
    ("color.text.inverse",
      ThemePair(light: "#f3f3f3", dark: "#f3f3f3")), # colors.ui.text.on-action.primary
    ("color.border.subtle",
      ThemePair(light: "#c8c2b5", dark: "#282828")), # colors.ui.divider.subtle
    ("color.accent.primary",
      ThemePair(light: "#a5b4fc", dark: "#4f46e5")), # colors.ui.surface.action.primary
    ("color.accent.primaryText",
      ThemePair(light: "#f3f3f3", dark: "#f3f3f3")), # colors.ui.text.on-action.primary
    ("color.link",
      ThemePair(light: "#2563eb", dark: "#93c5fd")), # colors.ui.text.information.primary
    ("color.status.info",
      ThemePair(light: "#2563eb", dark: "#93c5fd")), # colors.ui.text.information.primary
    ("color.status.info.bg",
      ThemePair(light: "#dbeafe", dark: "#1e3a8a")), # light token colors.information.100 / dark token colors.information.900
    ("color.status.success",
      ThemePair(light: "#16a34a", dark: "#bbf7d0")), # colors.ui.text.success.primary
    ("color.status.success.bg",
      ThemePair(light: "#dcfce7", dark: "#14532d")), # light token colors.success.100 / dark token colors.success.900
    ("color.status.warning",
      ThemePair(light: "#ea580c", dark: "#fdba74")), # colors.ui.text.warning.primary
    ("color.status.warning.bg",
      ThemePair(light: "#ffedd5", dark: "#7c2d12")), # light token colors.warning.100 / dark token colors.warning.900
    ("color.status.danger",
      ThemePair(light: "#dc2626", dark: "#fca5a5")), # colors.ui.text.error.primary
    ("color.status.danger.bg",
      ThemePair(light: "#fee2e2", dark: "#7f1d1d")), # light token colors.error.100 / dark token colors.error.900
    ("font.body",
      ThemePair(light: "Helvetica, Arial, sans-serif", dark: "Helvetica, Arial, sans-serif")), # literal
    ("font.heading",
      ThemePair(light: "Helvetica, Arial, sans-serif", dark: "Helvetica, Arial, sans-serif")), # literal
    ("font.mono",
      ThemePair(light: "Menlo, Consolas, 'Courier New', monospace", dark: "Menlo, Consolas, 'Courier New', monospace")), # literal
    ("type.body",
      ThemePair(light: "16px/24px", dark: "16px/24px")), # literal
    ("type.small",
      ThemePair(light: "14px/20px", dark: "14px/20px")), # literal
    ("type.h1",
      ThemePair(light: "28px/36px/700", dark: "28px/36px/700")), # literal
    ("type.h2",
      ThemePair(light: "22px/30px/700", dark: "22px/30px/700")), # literal
    ("type.h3",
      ThemePair(light: "18px/26px/700", dark: "18px/26px/700")), # literal
    ("space.1",
      ThemePair(light: "4px", dark: "4px")), # literal
    ("space.2",
      ThemePair(light: "8px", dark: "8px")), # literal
    ("space.3",
      ThemePair(light: "12px", dark: "12px")), # literal
    ("space.4",
      ThemePair(light: "16px", dark: "16px")), # literal
    ("space.5",
      ThemePair(light: "24px", dark: "24px")), # literal
    ("space.6",
      ThemePair(light: "32px", dark: "32px")), # literal
    ("space.7",
      ThemePair(light: "48px", dark: "48px")), # literal
    ("space.8",
      ThemePair(light: "64px", dark: "64px")), # literal
    ("space.section",
      ThemePair(light: "24px 0", dark: "24px 0")), # literal
    ("space.gutter",
      ThemePair(light: "0 24px", dark: "0 24px")), # literal
    ("radius.sm",
      ThemePair(light: "4px", dark: "4px")), # literal
    ("radius.md",
      ThemePair(light: "6px", dark: "6px")), # literal
    ("radius.lg",
      ThemePair(light: "12px", dark: "12px")), # literal
    ("button.padding",
      ThemePair(light: "12px 24px", dark: "12px 24px")), # literal
    ("button.font",
      ThemePair(light: "16px/20px/600", dark: "16px/20px/600")), # literal
    ("layout.containerWidth",
      ThemePair(light: "600", dark: "600")), # literal
    ("layout.breakpoint",
      ThemePair(light: "480", dark: "480")), # literal
  ], "metacraftTheme")
