"""tools/text-metrics/generate.py — the text-metrics table generator.

Reads the advance widths of the metric-compatible fonts the capture
environment pins (Liberation Sans, Serif and Mono for Arial, Times and
Courier; Carlito for Calibri; Roboto; Noto Sans for every other family)
with fonttools, and writes `src/isonim_email/metrics_data.nim`: per face
(regular and bold), the advance of every character of the Basic Latin,
Latin-1 Supplement, Latin Extended-A and General Punctuation ranges in
font units, the face's units per em, and the sha256 of the font file it
was read from, and its average advance over every character its
character map holds (zero-width marks aside): Noto Sans' average stands
in for characters outside those ranges.

The fonts are located with `fc-match` under the dev shell's
`FONTCONFIG_FILE` (the pinned font set the captures render with), so
the table is the fonts the captures use. The output depends on the font
bytes only (no store paths, no dates): regenerating on the same fonts is
a byte-identical no-op, and `tests/t3_metrics_reproducible.nim` checks both the
hashes and the regeneration.

Usage: generate.py <out.nim>   (run by `just text-metrics`)
"""

import hashlib
import os
import subprocess
import sys

from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

# (key, fontconfig pattern, file basename the pattern must resolve to)
FACES = [
    ("liberationSans", "Liberation Sans:style=Regular", "LiberationSans-Regular.ttf"),
    ("liberationSansBold", "Liberation Sans:style=Bold", "LiberationSans-Bold.ttf"),
    ("liberationSerif", "Liberation Serif:style=Regular", "LiberationSerif-Regular.ttf"),
    ("liberationSerifBold", "Liberation Serif:style=Bold", "LiberationSerif-Bold.ttf"),
    ("liberationMono", "Liberation Mono:style=Regular", "LiberationMono-Regular.ttf"),
    ("liberationMonoBold", "Liberation Mono:style=Bold", "LiberationMono-Bold.ttf"),
    ("carlito", "Carlito:style=Regular", "Carlito-Regular.ttf"),
    ("carlitoBold", "Carlito:style=Bold", "Carlito-Bold.ttf"),
    ("roboto", "Roboto:style=Regular", "Roboto-Regular.ttf"),
    ("robotoBold", "Roboto:style=Bold", "Roboto-Bold.ttf"),
    # Noto Sans is a variable font: read at weight 400 and 700.
    ("notoSans", "Noto Sans:style=Regular", "NotoSans.ttf"),
    ("notoSansBold", "Noto Sans:style=Bold", "NotoSans.ttf"),
]

RANGES = [(0x20, 0x7E), (0xA0, 0xFF), (0x100, 0x17F), (0x2000, 0x206F)]


def locate(pattern, basename):
    path = subprocess.run(
        ["fc-match", "-f", "%{file}", pattern],
        check=True, capture_output=True, text=True).stdout.strip()
    if os.path.basename(path) != basename:
        sys.exit("generate.py: fc-match '%s' gave %s, not %s (is the dev "
                  "shell's FONTCONFIG_FILE in effect?)" % (pattern, path, basename))
    return path


def face_data(path, bold):
    with open(path, "rb") as f:
        digest = hashlib.sha256(f.read()).hexdigest()
    font = TTFont(path)
    if "fvar" in font:
        # A variable font: the advances of the named weight's instance.
        font = instancer.instantiateVariableFont(
            font, {"wght": 700 if bold else 400})
    upem = font["head"].unitsPerEm
    cmap = font.getBestCmap()
    hmtx = font["hmtx"]
    advances = []
    for lo, hi in RANGES:
        for cp in range(lo, hi + 1):
            glyph = cmap.get(cp)
            # 0: the face has no glyph for the character.
            advances.append(hmtx[glyph][0] if glyph is not None else 0)
    total = count = 0
    for cp, glyph in sorted(cmap.items()):
        adv = hmtx[glyph][0]
        if adv > 0:
            total += adv
            count += 1
    average = (total + count // 2) // count
    return digest, upem, advances, average


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: generate.py <out.nim>")
    lines = [
        "## isonim_email/metrics_data.nim — GENERATED by",
        "## tools/text-metrics/generate.py (`just text-metrics`); do not edit.",
        "##",
        "## Advance widths in font units, per face, for U+0020–U+007E,",
        "## U+00A0–U+00FF, U+0100–U+017F and U+2000–U+206F, in that order",
        "## (0 = no glyph). Read from these font files (sha256):",
    ]
    data = []
    for key, pattern, basename in FACES:
        digest, upem, advances, average = face_data(
            locate(pattern, basename), key.endswith("Bold"))
        lines.append("##   %s  %s" % (digest, basename))
        data.append((key, basename, digest, upem, advances, average))
    count = len(data[0][4])
    lines += [
        "",
        "import ./target",
        "",
        "## The client families an edit to this module can change: read by",
        "## the capture CLI to pick the families of an `--affected` run.",
        "const affects*: set[ClientFamily] = allFamilies",
        "",
        "const",
        "  metricsGlyphCount* = %d" % count,
        "    ## Characters per face.",
        "  metricsRanges*: array[%d, (int, int)] = [%s]" % (
            len(RANGES), ", ".join("(0x%04X, 0x%04X)" % r for r in RANGES)),
        "    ## The covered ranges, in table order.",
        "",
        "type MetricsFace* = object",
        "  file*, sha256*: string",
        "  unitsPerEm*: int",
        "  averageAdvance*: int ## over every mapped character",
        "  advances*: array[%d, int16]" % count,
        "",
    ]
    for key, basename, digest, upem, advances, average in data:
        lines.append("const %sFace* = MetricsFace(file: \"%s\"," % (key, basename))
        lines.append("  sha256: \"%s\"," % digest)
        lines.append("  unitsPerEm: %d, averageAdvance: %d, advances: [" % (upem, average))
        cells = ["%d'i16" % advances[0]] + ["%d" % a for a in advances[1:]]
        for i in range(0, count, 12):
            lines.append("    " + ", ".join(cells[i:i + 12]) + ",")
        lines[-1] = lines[-1].rstrip(",") + "])"
        lines.append("")
    out = "\n".join(lines).rstrip("\n") + "\n"
    with open(sys.argv[1], "w", encoding="utf-8", newline="\n") as f:
        f.write(out)


if __name__ == "__main__":
    main()
